### ISSUE TITLE
Fix typo

### ISSUE THREAD

**Issue by MineralwaterXu** [sjlleo/local-ISPs-to-CN#9]
From 27f224da5ab7df6a55bf7d8e7f2af6960a09ee58 Mon Sep 17 00:00:00 2001
From: Mineralwater Xu <mineralwater@m1neralwater.com>
Date: Tue, 10 May 2022 23:44:05 +0800
Subject: [PATCH] Fix typo

---
 report_zh_CN.md | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/report_zh_CN.md b/report_zh_CN.md
index b27ea64..9c6e09d 100644
--- a/report_zh_CN.md
+++ b/report_zh_CN.md
@@ -189,7 +189,7 @@ AS58453：CMI > CUG > SingTel > HKIX > NTT > HKBN/WTT > Others
 
 移动如果不买他们的商业高Qos宽带，在高峰时期直连NTT会被Qos，丢包和延时都会显著增加，速度一般无法超过10Mbps。对于高Qos的移动用户也并不乐观，高峰时期，因为上海和广州地区汇聚层拥堵显著，所以最高速率往往也无法超过200Mbps
 
-特殊CM2精品网大客户除外，此类客户购买了移动的国际加速业务，移动优先保证此类 VIP 付费客户的宽带，Qos等级仅次于移动内网业务的必要控制流量，是所有运营类宽带里最高的，故除非PoP塞爆，否则在CMI和各大ISP的Peer下都会极力保证合同签约速率，哪怕是NTT、Cogent这些平时流量极大的网络都可以做到插队绿色通道。
+特殊CN2精品网大客户除外，此类客户购买了移动的国际加速业务，移动优先保证此类 VIP 付费客户的宽带，Qos等级仅次于移动内网业务的必要控制流量，是所有运营类宽带里最高的，故除非PoP塞爆，否则在CMI和各大ISP的Peer下都会极力保证合同签约速率，哪怕是NTT、Cogent这些平时流量极大的网络都可以做到插队绿色通道。
 
 **PCCW（香港）/HKT**
 
-- 
2.36.1

**Comment by sjlleo** [comment]
您好，CM2是存在的，是移动的试图仿照CN2建设的新骨干网，主要用于国际优化方向等用途，目前对于其更多消息尚不明确。

**Comment by MineralwaterXu** [comment]
没有结合上下文正确理解内容非常抱歉。
